version: '3.8'
services:
  pgdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /pgdata/data:/var/lib/postgresql-demo/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}